### ISSUE TITLE
Create login behavior from tracker for training app v2

### ISSUE THREAD

**Issue by Ezmeyers** [iupui-soic/mHBS_tracker#110]
- [x] Send broadcast to tracker capture app
According to [this stack overflow post](https://stackoverflow.com/questions/43937839/receiving-broadcast-intents-with-cordova-broadcaster?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa) the cordova broadcaster only handles sending to LocalBroadcastManager for in app communication, but it's okay because the [intent plugin](https://www.npmjs.com/package/com-darryncampbell-cordova-plugin-intent) @sunbiz suggested already handles this, so I was able to complete and confirm the broadcast

- [x] Receive the login information in response

- [x]  Log the user in via javascript

**Comment by Ezmeyers** [comment]
Took me awhile to figure this out, but com-darryncampbell-cordova-plugin-intent does not handle intent.action.main nor does it support string arrays. However [napolitano does](https://github.com/napolitano/cordova-plugin-intent) and the intent works for our purpose, so I am using darry's plugin for the broadcast and napolitano to grab the data from tracker.

**Comment by Ezmeyers** [comment]
complete @https://github.com/Ezmeyers/mHBS_Hybridapp/commit/79b07686494744866d7bf0bb98373bbf3bdb3e64

**Comment by sunbiz** [comment]
Tested with modifications in #175
