### ISSUE TITLE
Update on form creation on DHIS2

### ISSUE THREAD

**Issue by sivaadde** [iupui-soic/mHBS_tracker#40]
@iupui-soic/mhbs-muri This is just to track progress on form creation process in DHIS2.  

- [ ] Learner Registration Form #1
- [ ] Pre-assessment Form #2
- [x] Knowledge Check #4
- [x] BMV Skill Check #5
- [x] OSCE A #6
- [x] OSCE B #7
- [x] Resuscitation debriefing Form #8
- [x] Perinatal Death Audit #9
- [ ] Self Reporting of trianing and practice for providers #11
- [x] Delivery Checklist #12 
- [x] Quality improvement monitoring visit checklist #13

**Comment by Ezmeyers** [comment]
@sivaadde #4 #5 #6 and #7 are finished except for scoring options....so we can't really consider they are "done." I think #2 was done by @tchilders95 but I'm not sure about that one.

**Comment by Ezmeyers** [comment]
On #12 Delivery Checklist other options were not added

**Comment by shbucher** [comment]
The templates for the resuscitation debriefing form and perinatal death audits form have been uploaded to the comments on the original issues.  These forms are important, as is the Delivery Observation Form, as they contain fields for numerators and denominators from which some of our key indicators will be aggregated. FYI, @phoenigmatic

**Comment by sunbiz** [comment]
- Delivery checklist needs to be made available to the RA role
- QI improvement checklist is now called "Health Facility Site Visit Form" available only to the RA role
- Aggregate forms should only be available to the RA role and PIs

"Self reporting of training and practice form" will be "HBB corner log"
And @shbucher will verify if the OSCEs, BMV and MCQ should be available to all users or RA only.

**Comment by BhavaniSingh** [comment]
Knowledge check, delivery and HBB activity log are the only forms that should be available to Trainee(s).
RAs should be able to see all the forms in helping babies breathe program.

**Comment by SherriBucher** [comment]
DHIS2 Tracker forms for the eHBB/mHBS study tool (mHBS Research) are finalized.

Final PDFs sent to UW collaborators 30 January 2019.

In the end, collaborators determined that the only forms open to Trainees on the mHBS/eHBB research tool should be Knowledge Check, Delivery and HBB Activity Log, and, at the end of the 6 month trial period, Follow-Up Survey.  All other forms visible to the Research Assistants.

It was decided that the HBB activity logs (daily practice at HBB corners) should be on paper.  There is a section for the RAs in the Health Facility Site Visit form to record if the paper log has been filled, and to take a photo of the log if this is the case.

[1_Knowledge_check__mHBS research tool_eHBB_January 2019-FINAL.pdf](https://github.com/iupui-soic/mHBS_tracker/files/2817722/1_Knowledge_check__mHBS.research.tool_eHBB_January.2019-FINAL.pdf)
[2_BMV_Skills_Check__mHBS research tool_eHBB_January 2019-FINAL .pdf](https://github.com/iupui-soic/mHBS_tracker/files/2817724/2_BMV_Skills_Check__mHBS.research.tool_eHBB_January.2019-FINAL.pdf)
[3_OSCE_A__mHBS research tool_eHBB_January 2019-FINAL (1).pdf](https://github.com/iupui-soic/mHBS_tracker/files/2817727/3_OSCE_A__mHBS.research.tool_eHBB_January.2019-FINAL.1.pdf)
[4_OSCE_B__mHBS research tool_eHBB_January 2019-FINAL (1).pdf](https://github.com/iupui-soic/mHBS_tracker/files/2817729/4_OSCE_B__mHBS.research.tool_eHBB_January.2019-FINAL.1.pdf)
[5_Health_facility_site_visit__mHBS research tool_eHBB_January 2019-FINAL.pdf](https://github.com/iupui-soic/mHBS_tracker/files/2817731/5_Health_facility_site_visit__mHBS.research.tool_eHBB_January.2019-FINAL.pdf)
[6_Delivery_Observation_Checklist__mHBS research tool_eHBB_January 2019-FINAL.pdf](https://github.com/iupui-soic/mHBS_tracker/files/2817732/6_Delivery_Observation_Checklist__mHBS.research.tool_eHBB_January.2019-FINAL.pdf)
[7_Perinatal_Death_Audit__mHBS research tool_eHBB_January 2019-FINAL.pdf](https://github.com/iupui-soic/mHBS_tracker/files/2817733/7_Perinatal_Death_Audit__mHBS.research.tool_eHBB_January.2019-FINAL.pdf)
[8_Resuscitation_Debriefing__mHBS research tool_eHBB_January 2019-FINAL.pdf](https://github.com/iupui-soic/mHBS_tracker/files/2817734/8_Resuscitation_Debriefing__mHBS.research.tool_eHBB_January.2019-FINAL.pdf)
[9_Delivery_and_HBB_Activity_Log__mHBS research tool_eHBB_January 2019-FINAL.pdf](https://github.com/iupui-soic/mHBS_tracker/files/2817735/9_Delivery_and_HBB_Activity_Log__mHBS.research.tool_eHBB_January.2019-FINAL.pdf)
[10_Follow_Up_Survey__mHBS research tool_eHBB_January 2019-FINAL.pdf](https://github.com/iupui-soic/mHBS_tracker/files/2817737/10_Follow_Up_Survey__mHBS.research.tool_eHBB_January.2019-FINAL.pdf)
